### ISSUE TITLE
Comune mancante: 00050 ARA NOVA (Fiumicino) RM

### ISSUE THREAD

**Issue by andrea-magni** [matteocontrini/comuni-json#19]
Ciao, grazie per il tuo progetto utilissimo!
Manca un comune, anzi forse più di uno: 
https://www.nonsolocap.it/cap?k=00050&b=+Cerca+&c=

**Comment by matteocontrini** [comment]
Ciao, premesso che Ara Nova non è un comune ma una frazione, se manca un CAP di una frazione nel database purtroppo è difficile farci qualcosa... ci sono alcuni comuni che hanno CAP diversi per le frazioni, ma è difficile raccoglierli dato che spesso non sono nemmeno indicati sui siti ufficiali dei comuni.

Problemi simili sono stati segnalati in #16 e #10, ma non saprei come procedere.

**Comment by andrea-magni** [comment]
Non potremmo integrarli? Se hai un processo automatico che compila il tuo file JSON a partire dagli archivi ufficiali, potresti, a valle, aggiungere anche questi comuni/frazioni "segnalati a mano" magari con un attributo che indica il fatto che sono stati aggiunti a mano.

Che ne dici?

**Comment by matteocontrini** [comment]
Si può, però non possiamo sapere quanti altri ce ne sono. Senza considerare che i CAP cambiano e non sempre Poste comunica quelli nuovi...

Se vuoi aggiungere manualmente qualche CAP non rifiuto :) puoi creare una PR, e per aggiungere un CAP devi:

- trovare il file corrispondente al comune nella cartella `data`. Il nome del file contiene il codice ISTAT, per facilitare la ricerca
- aggiungere il CAP al campo `cap`, che è un array

Poi penso io alla "compilazione" del file comuni.json (che comunque viene fatta con uno script presente nella repository).

**Comment by matteocontrini** [comment]
Ah e a proposito del flag "segnalati a mano", ormai tutti i CAP del file sono aggiornati a mano, man mano che Poste li comunica. Non esiste un archivio ufficiale, o meglio è a pagamento, che poi è il motivo per cui esiste questa repository.

**Comment by SARTrack** [comment]
Hello,
I am trying to install and run the ScannerMapp, in both Delphi 10.2.3 and 10.3 (Beta).
I can compile and install the TFrameStand OKAY in both 10.2 and 10.3 (Beta) but when I load the ScannerMapp I get a warning about a missing Dependency (without any name) followed by a "Cannot load data from server". and when I try to compile it, I get a fatal error:
[MSBuild Error] The "GetItCmd" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Borland.Build.Tasks.Common.CommandLineTask.Execute()
   at Borland.Build.Tasks.Shared.GetItCmd.Execute()
   at Microsoft.Build.BuildEngine.TaskEngine.ExecuteInstantiatedTask(EngineProxy engineProxy, ItemBucket bucket, TaskExecutionMode howToExecuteTask, ITask task, Boolean& taskResult)

This happens in both compilers.
Can you tell me what I do wrong? I would really like a reply be Email if possible, at ceo@sartrack.nz

Thanks,  Bart Kindt
New Zealand
www.sartrack.nz
